mixed-port: 7890
allow-lan: true
bind-address: '*'
ipv6: false
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 223.6.6.6
  nameserver:
    - https://dns.alidns.com/dns-query
  nameserver-policy:
    'talk.google.com': 108.177.125.188
    'mtalk.google.com': 108.177.125.188
    'alt1-mtalk.google.com': 3.3.3.3
    'alt2-mtalk.google.com': 3.3.3.3
    'alt3-mtalk.google.com': 74.125.200.188
    'alt4-mtalk.google.com': 74.125.200.188
    'alt5-mtalk.google.com': 3.3.3.3
    'alt6-mtalk.google.com': 3.3.3.3
    'alt7-mtalk.google.com': 74.125.200.188
    'alt8-mtalk.google.com': 3.3.3.3
    'blog.google': https://doh.pub/dns-query
    'googletraveladservices.com': https://doh.pub/dns-query
    'dl.google.com': https://doh.pub/dns-query
    'dl.l.google.com': https://doh.pub/dns-query
    'clientservices.googleapis.com': https://doh.pub/dns-query
    'update.googleapis.com': https://doh.pub/dns-query
    'translate.googleapis.com': https://doh.pub/dns-query
    'fonts.googleapis.com': https://doh.pub/dns-query
    'fonts.gstatic.com': https://doh.pub/dns-query
    '*.tencent.com': https://doh.pub/dns-query
    '*.qcloud.com': https://doh.pub/dns-query
    '*.qcloudcdn.cn': https://doh.pub/dns-query
    '*.qcloudcdn.com': https://doh.pub/dns-query
    '*.qcloudcos.com': https://doh.pub/dns-query
    '*.qcloudimg.com': https://doh.pub/dns-query
    '*.qcloudcjgj.com': https://doh.pub/dns-query
    '*.qcloudwzgj.com': https://doh.pub/dns-query
    '*.qcloudzygj.com': https://doh.pub/dns-query
    '*.myqcloud.com': https://doh.pub/dns-query
    '*.tencent-cloud.net': https://doh.pub/dns-query
    '*.tencentcloud-aiot.com': https://doh.pub/dns-query
    '*.tencentcloudapi.com': https://doh.pub/dns-query
    '*.tencentcloudcr.com': https://doh.pub/dns-query
    '*.tencentcloudmarket.com': https://doh.pub/dns-query
    '*.qq.com': https://doh.pub/dns-query
    '*.qlogo.cn': https://doh.pub/dns-query
    '*.qpic.cn': https://doh.pub/dns-query
    '*.weixin.qq.com': https://doh.pub/dns-query
    '*.wx.qq.com': https://doh.pub/dns-query
    '*.weixin.com': https://doh.pub/dns-query
    '*.weixin.qq.com.cn': https://doh.pub/dns-query
    '*.wxs.qq.com': https://doh.pub/dns-query
    '*.tc.qq.com': https://doh.pub/dns-query
    '*.urlsec.qq.com': https://doh.pub/dns-query
    '*.weixinbridge.com': https://doh.pub/dns-query
    '*.wechat.com': https://doh.pub/dns-query
    '*.servicewechat.com': https://doh.pub/dns-query
    '*.weiyun.com': https://doh.pub/dns-query
    '*.gtimg.cn': https://doh.pub/dns-query
    '*.idqqimg.com': https://doh.pub/dns-query
    '*.cdn-go.cn': https://doh.pub/dns-query
    '*.smtcdns.com': https://doh.pub/dns-query
    '*.smtcdns.net': https://doh.pub/dns-query
    'url.cn': https://doh.pub/dns-query
    '*.baidu': 180.76.76.76
    '*.baidu.com': 180.76.76.76
    '*.bdimg.com': 180.76.76.76
    '*.bdstatic.com': 180.76.76.76
    '*.baidupcs.*': 180.76.76.76
    '*.baiduyuncdn.*': 180.76.76.76
    '*.baiduyundns.*': 180.76.76.76
    '*.bdydns.*': 180.76.76.76
    '*.bdycdn.*': 180.76.76.76
    '*.bdysite.com': 180.76.76.76
    '*.bdysites.com': 180.76.76.76
    '*.baidubce.*': 180.76.76.76
    '*.bcedns.*': 180.76.76.76
    '*.bcebos.com': 180.76.76.76
    '*.bcevod.com': 180.76.76.76
    '*.bceimg.com': 180.76.76.76
    '*.bcehost.com': 180.76.76.76
    '*.bcehosts.com': 180.76.76.76
    'dwz.cn': 180.76.76.76
    'localhost': 127.0.0.1
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - '*.linksys.com'
    - '+.pool.ntp.org'
    - localhost.ptlogin2.qq.com

proxies:

proxy-providers:

proxy-groups:
  - name: 最终代理
    type: select
    benchmark-url: http://1.1.1.1/generate_204
    benchmark-timeout: 3
    interval: 3600
    lazy: true
    include-all: true
    icon: https://raw.githubusercontent.com/Looksbsb/Stash_private_config/main/icon/new_icon/Internet.png

  - name: 电报吹水
    type: select
    include-all: true
    icon: https://raw.githubusercontent.com/Looksbsb/Stash_private_config/main/icon/new_icon/Telegram.png

  - name: 谷歌服务
    type: select
    include-all: true
    icon: https://raw.githubusercontent.com/Looksbsb/Stash_private_config/main/icon/new_icon/Google.png

  - name: 社交服务
    type: select
    include-all: true
    filter: 美國|美国|日本|US|JP
    icon: https://raw.githubusercontent.com/Looksbsb/Stash_private_config/main/icon/new_icon/Cat.png

  - name: 必应服务
    type: select
    include-all: true
    icon: https://raw.githubusercontent.com/Looksbsb/Stash_private_config/main/icon/new_icon/Bing.png
rule-providers:
  Telegram:
    behavior: classical
    url: https://github.com/Looksbsb/Rules/raw/main/stash/Telegram.txt
    interval: 604800
  Google:
    behavior: domain-text
    url: https://github.com/Looksbsb/Rules/raw/main/stash/Google.txt
    interval: 604800
  Instagram:
    behavior: domain-text
    url: https://github.com/Looksbsb/Rules/raw/main/stash/Instagram.txt
    interval: 604800
  Twitter:
    behavior: domain-text
    url: https://github.com/Looksbsb/Rules/raw/main/stash/Twitter.txt
    interval: 604800
  Spotify:
    behavior: domain-text
    url: https://github.com/Looksbsb/Rules/raw/main/stash/Spotify.txt
    interval: 604800
  Apple:
    behavior: domain-text
    url: https://github.com/Looksbsb/Rules/raw/main/stash/Apple.txt
    interval: 604800
  Mainland:
    behavior: domain-text
    url: https://github.com/Looksbsb/Rules/raw/main/stash/Mainland.txt
    interval: 604800

rules: 
  - DOMAIN-SUFFIX,app-measurement.com,REJECT,no-track
  - RULE-SET,Telegram,电报吹水
  - DOMAIN-SET,Instagram,社交服务
  - DOMAIN-SET,Twitter,社交服务
  - DOMAIN-SET,Google,谷歌服务
  - DOMAIN-SET,Spotify,谷歌服务
  - DOMAIN-SET,Apple,DIRECT
  - DOMAIN-SET,Mainland,DIRECT
  # 内容：Bing
  - DOMAIN-SUFFIX,appcenter.ms,必应服务
  - DOMAIN-SUFFIX,azure.com,必应服务
  - DOMAIN-SUFFIX,azureedge.net,必应服务
  - DOMAIN-SUFFIX,bing.com,必应服务
  - DOMAIN-SUFFIX,bingapis.com,必应服务
  - DOMAIN-SUFFIX,bluehatnights.com,必应服务
  - DOMAIN-SUFFIX,clarity.ms,必应服务
  - DOMAIN-SUFFIX,dictate.ms,必应服务
  - DOMAIN-SUFFIX,ditu.live.com,必应服务
  - DOMAIN-SUFFIX,flipwithsurface.com,必应服务
  - DOMAIN-SUFFIX,masalladeloslimites.com,必应服务
  - DOMAIN-SUFFIX,hotmail.com,必应服务
  - DOMAIN-SUFFIX,microsoft.com,必应服务
  - DOMAIN-SUFFIX,microsoft-falcon.io,必应服务
  - DOMAIN-SUFFIX,msn.cn,必应服务
  - DOMAIN-SUFFIX,msn.com,必应服务
  - DOMAIN-SUFFIX,msecnd.net,必应服务
  - DOMAIN-SUFFIX,msunlimitedcloudsummit.com,必应服务
  - DOMAIN-SUFFIX,outlook.com,必应服务
  - DOMAIN-SUFFIX,outlookmobile.com,必应服务
  - DOMAIN-SUFFIX,office365love.com,必应服务
  - DOMAIN-SUFFIX,office365tw.com,必应服务
  - DOMAIN-SUFFIX,onedrive.com,必应服务
  - DOMAIN-SUFFIX,renovacionoffice.com,必应服务
  - DOMAIN-SUFFIX,sprinklesapp.com,必应服务
  - DOMAIN-SUFFIX,scorecardresearch.com,必应服务
  - DOMAIN-SUFFIX,virtualearth.net,必应服务
  - DOMAIN-KEYWORD,bing,必应服务
  - DOMAIN-KEYWORD,microsoft,必应服务
#####################################
  - MATCH,最终代理
